#!/bin/bash
#
# Launch script for stk_gui

# export the location of a few files
export GDK_PIXBUF_MODULE_FILE="/Applications/STK.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export PANGO_RC_FILE="/Applications/STK.app/Contents/pango_rc"
/Applications/STK.app/Contents/bin/python /Applications/Diamond.app/Contents/lib/python2.7/site-packages/stk-1.0-py2.7.egg/EGG-INFO/scripts/stk_gui
