#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'trunk',
 'build_date': '2015-04-22 11:37:13 +0100',
 'clean': None,
 'date': '2015-04-16 08:25:40 +0100',
 'revision_id': 'jon.hill@imperial.ac.uk-20150416072540-407pgtxuyhis6crv',
 'revno': '271'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
