#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'sub_in_subfile',
 'build_date': '2015-10-07 16:33:20 +0100',
 'clean': None,
 'date': '2015-09-17 07:45:13 +0100',
 'revision_id': 'jon.hill@york.ac.uk-20150917064513-9h4apc573s5cd8hc',
 'revno': '307'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
